<?php
/*
 * Very simple event field module for jQT Calendar rendering
 */

function simple_event_field_field_info() {
  return array(
    'simple_event' => array(
      'label' => t('Simple Event'),
      'description' => t('Stores a date, time and short description'),
    )
  );
}

/* Default hooks */
function simple_event_field_install() {
  content_notify('install', 'simple_event');
}
function simple_event_field_uninstall() {
  content_notify('install', 'simple_event');
}
function simple_event_field_enable() {
  content_notify('install', 'simple_event');
}
function simple_event_field_disable() {
  content_notify('install', 'simple_event');
}

/* Settings */
function person_fld_field_settings($op, $field) {
  switch ($op) {
    case 'database columns':
      $columns['displayed_name'] = array('type' => 'varchar', 'length' => 255, 'not null' => FALSE, 'sortable' => TRUE, 'default' => '');
      $columns['job_title'] = array('type' => 'varchar', 'length' => 255, 'not null' => FALSE, 'sortable' => TRUE, 'default' => '');
      $columns['phone'] = array('type' => 'varchar', 'length' => 255, 'not null' => FALSE, 'sortable' => FALSE, 'default' => '');
      $columns['email'] = array('type' => 'varchar', 'length' => 255, 'not null' => FALSE, 'sortable' => FALSE, 'default' => '');
      return $columns;
  }
}